# Generated by Django 4.1.7 on 2023-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=250)),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
